name: Run Wildberries Bot

on:
  push:
    branches:
      - main  # или ваша основная ветка

jobs:
  run-wildberries-bot:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./botWB  # запуск из папки botWB

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.5'  # укажите нужную версию Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r botWB/requirements.txt

    - name: Create Google credentials file
      run: echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}' > credentials.json
      shell: bash

    - name: Run Wildberries Review Script
      run: python "botWB/avto_scan_wb(my).py"
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        EMAIL_LOGIN: ${{ secrets.EMAIL_LOGIN }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        GOOGLE_APPLICATION_CREDENTIALS: credentials.json
        GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}

    - name: Save generated reports as artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: wildberries-reports
        path: |
          *.txt
